modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/nvb-uy/Spell_Engine_OPAC_Compat/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/nvb-uy/Spell_Engine_OPAC_Compat"
logoFile="assets/spell-engine-openpac-compat/icon.png"
authors="${mod_authors}"
description='''
Adds party and alliance protection from Open Parties and Claims to Spell Engine targeting.
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="spell_engine"
type="required"
versionRange="${spell_engine_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="openpartiesandclaims"
type="required"
versionRange="${opac_version_range}"
ordering="AFTER"
side="BOTH"
